inherit_from: [experiments/config_base_3RScan_full_l20.yaml,experiments/config_base_VGfM.yaml]
name: 'VGfM_full_l20_6_test'
training:
 data_workers: 0
model:
 multi_rel: false
data:
 path: "./data/3RScan_ScanNet20_gt_10/"
 path_gt: "./data/3RScan_ScanNet20_gt_10/"
wandb:
 dry_run: true
 tags: ["ssg", "vgfm",'full','l20']
