inherit_from: [experiments/config_base_3RScan_orbslam_l20.yaml,experiments/config_base_3DSSG.yaml]
name: '3DSSG_3rscan_orbslam_l20_0'
training:
  batch: 1
  data_workers: 4
model:
 multi_rel: false # multiple relationship 
 use_rgb: false # color is also bad
 use_normal: false # no normal for orbslam ply file
data:
 load_cache: true
wandb:
 dry_run: false
 tags: ["ssg", "3dssg","orbslam","l20"]