# Use attention-based MVCNN
inherit_from: [experiments/config_base_3RScan_orbslam_l20.yaml, experiments/config_base_2DSSG.yaml]
name: '2DSSG_orbslam_l20_2'
training:
 data_workers: 4
eval: #evaluation
 mode: instance #eval on [segment, instance].  
model:
 multi_rel: false
data:
 is_roi_img: true
 load_images: true
 load_points: false
 load_cache: false
 img_desc_6_pts: false # return 6 extreme points 
 drop_img_edge: 4 # if is int and >0, select given number. if is float/double, select percentage between [1-x,1]
 use_precompute_img_feature: false
wandb:
 dry_run: false
 tags: ["ssg", "2dssg",'orbslam','l20']
