inherit_from: [experiments/config_base_3RScan_orbslam_l20.yaml,experiments/config_base_VGfM.yaml]
name: 'VGfM_orbslam_l20_0'
training:
 data_workers: 4
model:
 multi_rel: false # multiple relationship 
eval: #evaluation
 mode: instance #eval on [segment, instance].  
wandb:
 dry_run: false
 tags: ["ssg", "vgfm",'orbslam','l20']
