inherit_from: [experiments/config_base_3RScan_orbslam_l20.yaml,experiments/config_base_IMP.yaml]
name: 'IMP_orbslam_l20_0'
training:
 data_workers: 4
model:
 multi_rel: false # multiple relationship 
wandb:
 dry_run: false
 tags: ["ssg", "imp",'orbslam','l20']
