inherit_from: [experiments/config_base_3RScan_orbslam_l20_2.yaml, experiments/config_base_JointSSG.yaml]
name: 'JointSSG_orbslam_l20_10_1' # 
training:
 batch: 1
 data_workers: 8
 validate_every: 2 # ignore validation in dev
model:
 use_rgb: false # color is also bad
 use_normal: false # no normal for orbslam ply file
 node_feature_dim: 512
 spatial_encoder:
  method: fc #[none,fc]
  dim: 128
 edge_encoder:
  method: 2dssg_1 # [basic,sgfn,2dssg, 2dssg_1]
  with_bn: false
 gnn:
  jointgnn:
   version: "v2"
   pts_msg_method: MSG_FAN
   img_msg_method: MSG_MV_DIRECT
  MSG_FAN:
   aggr: 'max'
   dim_atten: 256
   num_layers: 2
   num_heads: 8
   drop_out: 0.3
   use_bn: false
  MSG_MV_DIRECT:
   aggr: mean
   use_res: false
  MSG_MV_GAT:
   aggr: mean
  MSG_MV_SDPA:
   aggr: add
   num_heads: 8
  MSG_MV_FAN:
   aggr: max
   num_heads: 8
  MSG_FAN:
   aggr: 'max'
   num_heads: 8
   use_bn: false
   attn_dropout: 0.5
data:
 edge_desc: 'roi'# [roi,pts]
 load_cache: false
 img_desc_6_pts: true # return 6 extreme points 
 drop_img_edge: 4 # if is int and >0, select given number. if is float/double, select percentage between [1-x,1]
 use_precompute_img_feature: false
wandb:
 dry_run: false
 tags: ["ssg", "jointSSG",'orbslam','l20']
