inherit_from: configs/config_default.yaml
data:
 path: "./data/3RScan_ScanNet20_gt/"
 path_gt: "./data/3RScan_ScanNet20_gt/"
 label_file: "labels.instances.align.annotated.v2.ply"
 roi_img_path: "./data/3RScan/roi_images.h5"