inherit_from: configs/config_default.yaml
data:
 load_cache: false
 path: "./data/3RScan_ScanNet20_2DSSG_ORBSLAM3_3/"
 path_seq: "./data/3RScan_ScanNet20_2DSSG_ORBSLAM3_3_seq/"
 path_gt: "./data/3RScan_ScanNet20_gt/"
 label_file: "2dssg_orbslam3.ply"
 label_file_seq: "2dssg_seq"
 roi_img_path: "${data.path_3rscan}/data/roi_2dssg_orbslam3/"
