inherit_from: [configs/dataset/config_base_3RScan_full_l20.yaml,configs/method/config_base_VGfM.yaml]
name: 'VGfM_full_l20_8'
model:
 multi_rel: false
wandb:
 dry_run: false
 tags: ["ssg", "vgfm",'full','l20']
