inherit_from: [configs/dataset/config_base_3RScan_full_l20.yaml,configs/method/config_base_SGFN.yaml]
training:
 batch: 64
model:
 multi_rel: false # multiple relationship 
data:
 load_catch: true
wandb:
 tags: ["ssg", "sgfn","full","l20"]
