inherit_from: [experiments/config_base_3RScan_full_l20.yaml,experiments/config_base_3DSSG.yaml]
name: '3DSSG_full_l20_3'
model:
 multi_rel: false # multiple relationship
data:
 load_cache: true
wandb:
 dry_run: false
 tags: ["ssg", "3dssg",'full','l20']
