inherit_from: [configs/dataset/config_base_3RScan_inseg_l20.yaml, configs/method/config_base_JointSSG.yaml]
model:
 multi_rel: false # multiple relationship 
wandb:
 tags: ["ssg", "jointSSG",'inseg','l20']
