inherit_from: [configs/dataset/config_base_3RScan_orbslam_l20_3.yaml,configs/method/config_base_IMP.yaml]
name: 'IMP_orbslam_l20_1'
model:
 multi_rel: false # multiple relationship 
wandb:
 dry_run: false
 tags: ["ssg", "imp",'orbslam','l20']
