inherit_from: [configs/dataset/config_base_3RScan_orbslam_l20.yaml,configs/method/config_base_SGFN.yaml]
training:
 batch: 2
 data_workers: 0
model:
 multi_rel: false # multiple relationship 
wandb:
 tags: ["ssg", "sgfn","orbslam","l20"]
