inherit_from: [configs/dataset/config_base_3RScan_full_l160.yaml, configs/method/config_base_JointSSG.yaml]
name: 'JointSSG_full_l160_0'
model:
 multi_rel: true # multiple relationship
data:
 load_cache: false
wandb:
 dry_run: false
 tags: ["ssg", "jointSSG",'full','l160']