inherit_from: [configs/dataset/config_base_3RScan_full_l160.yaml,configs/method/config_base_IMP.yaml]
name: 'IMP_FULL_l160_2_3'
model:
 multi_rel: true # multiple relationship 
wandb:
 dry_run: false
 tags: ["ssg", "imp",'full','l160']
