inherit_from: [configs/dataset/config_base_3RScan_inseg_l20.yaml,configs/method/config_base_IMP.yaml]
name: 'IMP_INSEG_l20_3'
model:
 multi_rel: false # multiple relationship 
wandb:
 dry_run: false
 tags: ["ssg", "imp",'inseg','l20']
